version : "3"
services :
  db:
    container_name: db
    restart: always
    image : postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=minh123
      - POSTGRES_USER=minh
      - POSTGRES_DB=test